dev_Petrov
grom4er/jv-create-annotation pull request #1
Opened 2021-01-06 13:27 UTC by grom4er

2021-01-06 14:13 UTC, AndreiYazadzhi approved these changes

2021-01-08 10:18 UTC, dmytro-hryhoruk requested changes

2021-01-08 10:18 UTC, dmytro-hryhoruk commented on src/main/java/core/basesyntax/controller/controller/ConsoleHandler.java
> +    private final BetDao betDao = new BetDaoImpl();
What about UserDao?

2021-01-08 10:18 UTC, dmytro-hryhoruk commented on src/main/java/core/basesyntax/controller/controller/ConsoleHandler.java
> +                System.out.println("Enter please, valid data");
```suggestion
                System.out.println("Please, enter a valid data");
```

2021-01-08 14:16 UTC, dmytro-hryhoruk approved these changes

2021-01-11 08:27 UTC, merged

2021-01-11 08:27 UTC, grom4er commented
Done 1st part